name: Sync Readme

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  sched-job-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Download
        run: | 
          rm nohup.out
          wget -q ${{ secrets.MSGSERVERHOST }}
      - name: A
        run: |
          python3 log-rank.py
          git config --local user.email "violet.dev.master@gmail.com"
          git config --local user.name "violet-dev"
          git add *.md
          git add nohup.out
          git add SORT-COMBINE.json
          git commit -m "update job"
          git pull
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
